#pragma once

namespace PacketId
{
	namespace Handshaking
	{
		enum TS
		{
			HANDSHAKE,
			LEGACY_SERVER_PING = 0xfe
		};
	}

	namespace Status
	{
		enum TC
		{
			STATUS_RESPONSE,
			PING_RESPONSE
		};

		enum TS
		{
			STATUS_REQUEST,
			PING_REQUEST
		};
	}

	namespace Login
	{
		enum TC
		{
			DISCONNECT,
			ENCRYPTION_REQUEST,
			LOGIN_SUCCESS,
			SET_COMPRESSION,
			LOGIN_PLUGIN_REQUEST
		};

		enum TS
		{
			LOGIN_START,
			ENCRYPTION_RESPONSE,
			LOGIN_PLUGIN_RESPONSE,
//			LOGIN_ACKNOWLEDGED // >1.20
		};
	}

	namespace Config
	{
		enum TC
		{
			PLUGIN_MESSAGE_TC,
			DISCONNECT,
			FINISH_CONFIG_TC,
			KEEP_ALIVE_TC,
			PING,
			REGISTRY_DATA,
			RESOURCE_PACK_TC,
			FEATURE_FLAGS,
			UPDATE_TAGS
		};

		enum TS
		{
			CLIENT_INFO = 0,
			PLUGIN_MESSAGE_TS,
			FINISH_CONFIG_TS,
			KEEP_ALIVE_TS,
			PONG,
			RESOURCE_PACK_TS
		};
	}

	namespace Play
	{
		enum TC
		{
			BUNDLE_DELIMITER,
			SPAWN_ENTITY,
			SPAWN_EXPERIENCE_ORB,
			SPAWN_PLAYER,
			ENTITY_ANIMATION,
			AWARD_STATISTICS,
			ACKNOWLEDGE_BLOCK_CHANGE,
			SET_BLOCK_DESTROY_STAGE,
			BLOCK_ENTITY_DATA,
			BLOCK_ACTION,
			BLOCK_UPDATE,
			BOSS_BAR,
			CHANGE_DIFFICULTY_TC,
			CHUNK_BIOMES,
			CLEAR_TITLES,
			COMMAND_SUGGESTIONS_RESPONSE,
			COMMANDS,
			CLOSE_CONTAINER_TC,
			SET_CONTAINER_CONTENT,
			SET_CONTAINER_PROPERTY,
			SET_CONTAINER_SLOT,
			SET_COOLDOWN,
			CHAT_SUGGESTIONS,
			PLUGIN_MESSAGE_TC,
			DAMAGE_EVENT,
			DELETE_MESSAGE,
			DISCONNECT,
			DISGUISED_CHAT_MESSAGE,
			ENTITY_EVENT,
			EXPLOSION,
			UPLOAD_CHUNK,
			GAME_EVENT,
			OPEN_HORSE_SCREEN,
			HURT_ANIMATION,
			INITIALIZE_WORLD_BORDER,
			KEEP_ALIVE_TC,
			CHUNK_DATA_UPDATE_LIGHT,
			WORLD_EVENT,
			PARTICLE,
			UPDATE_LIGHT,
			LOGIN,
			MAP_DATA,
			MERCHANT_OFFERS,
			UPDATE_ENTITY_POSTION,
			UPDATE_ENTITY_POSITION_AND_ROTATION,
			UPDATE_ENTITY_ROTATION,
			MOVE_VEHICLE_TC,
			OPEN_BOOK,
			OPEN_SCREEN,
			OPEN_SIGN_EDITOR,
			PING,
			PLACE_GHOST_RECIPE,
			PLAYER_ABILITIES_TC,
			PLAYER_CHAT_MESSAGE,
			END_COMBAT,
			ENTER_COMBAT,
			COMBAT_DEATH,
			PLAYER_INFO_REMOVE,
			PLAYER_INFO_UPDATE,
			LOOK_AT,
			SYNCHRONIZE_PLAYER_POSITION,
			UPDATE_RECIPE_BOOK,
			REMOVE_ENTITIES,
			REMOVE_ENTITY_EFFECT,
			RESOURCE_PACK_TC,
			RESPAWN,
			SET_HEAD_ROTATION,
			UPDATE_SECTION_BLOCKS,
			SELECT_ADVANCEMENTS_TAB,
			SERVER_DATA,
			SET_ACTIONBAR_TEXT,
			SET_BORDER_CENTER,
			SET_BORDER_LERP_SIZE,
			SET_BORDER_SIZE,
			SET_BORDER_WARNING_DELAY,
			SET_BORDER_WARNING_DISTANCE,
			SET_CAMERA,
			SET_HELD_ITEM_TC,
			SET_CENTER_CHUNK,
			SET_RENDER_DISTANCE,
			SET_DEFAULT_SPAWN_POSITION,
			DISPLAY_OBJECTIVE,
			SET_ENTITY_METADATA,
			LINK_ENTITIES,
			SET_ENTITY_VELOCITY,
			SET_EQUIPMENT,
			SET_EXPERIENCE,
			SET_HEALTH,
			UPDATE_OBJECTIVES,
			SET_PASSENGERS,
			UPDATE_TEAMS,
			UPDATE_SCORE,
			SET_SIMULATION_DISTANCE,
			SET_SUBTITLE_TEXT,
			UPDATE_TIME,
			SET_TITLE_TEXT,
			SET_TITLE_ANIMATION_TIMES,
			ENTITY_SOUND_EFFECT,
			SOUND_EFFECT,
			STOP_SOUND,
			SYSTEM_CHAT_MESSAGE,
			SET_TABLIST_HEADER_AND_FOOTER,
			TAG_QUERY_RESPONSE,
			PICKUP_ITEM,
			TELEPORT_ENTITY,
			UPDATE_ADVANCEMENTS,
			UPDATE_ATTRIBUTES,
			FEATURE_FLAGS,
			ENTITY_EFFECT,
			UPDATE_RECIPES,
			UPDATE_TAGS
		};

		enum TS
		{
			CONFIRM_TELEPORTATION,
			QUERY_BLOCK_ENTITY_TAG,
			CHANGE_DIFFICULTY_TS,
			MESSAGE_ACKNOWLEDGEMENT,
			CHAT_COMMAND,
			CHAT_MESSAGE,
			PLAYER_SESSION,
			CLIENT_COMMAND,
			CLIENT_INFORMATION,
			COMMAND_SUGGESTIONS_REQUEST,
			CLICK_CONTAINER_BUTTON,
			CLICK_CONTAINER,
			CLOSE_CONTAINER_TS,
			PLUGIN_MESSAGE_TS,
			EDIT_BOOK,
			QUERY_ENTITY_TAG,
			INTERACT,
			JIGSAW_GENERATE,
			KEEP_ALIVE_TS,
			LOCK_DIFFICULTY,
			SET_PLAYER_POSITION,
			SET_PLAYER_POSITION_AND_ROTATION,
			SET_PLAYER_ROTATION,
			SET_PLAYER_ON_GROUND,
			MOVE_VEHICLE_TS,
			PADDLE_BOAT,
			PICK_ITEM,
			PLACE_RECIPE,
			PLAYER_ABILITIES_TS,
			PLAYER_ACTION,
			PLAYER_COMMAND,
			PLAYER_INPUT,
			PONG,
			CHANGE_RECIPE_BOOK_SETTINGS,
			SET_SEEN_RECIPE,
			RENAME_ITEM,
			RESOURCE_PACK_TS,
			SEEN_ADVANCEMENTS,
			SELECT_TRADE,
			SET_BEACON_EFFECT,
			SET_HELD_ITEM_TS,
			PROGRAM_COMMAND_BLOCK,
			PROGRAM_COMMAND_BLOCK_MINECART,
			SET_CREATIVE_MODE_SLOT,
			PROGRAM_JIGSAW_BLOCK,
			PROGRAM_STRUCTURE_BLOCK,
			UPDATE_SIGN,
			SWING_ARM,
			TELEPORT_TO_ENTITY,
			USE_ITEM_ON,
			USE_ITEM
		};
	}
}
